// @generated by `cargo run -p conformance --bin generate`.
// DO NOT EDIT MANUALLY.

#[path = "gen/basic.rs"]
#[allow(clippy::all)]
mod basic;
#[path = "gen/bindings_ext.rs"]
#[allow(clippy::all)]
mod bindings_ext;
#[path = "gen/block_ext.rs"]
#[allow(clippy::all)]
mod block_ext;
#[path = "gen/comparisons.rs"]
#[allow(clippy::all)]
mod comparisons;
#[path = "gen/conversions.rs"]
#[allow(clippy::all)]
mod conversions;
#[path = "gen/dynamic.rs"]
#[allow(clippy::all)]
mod dynamic;
#[path = "gen/encoders_ext.rs"]
#[allow(clippy::all)]
mod encoders_ext;
#[path = "gen/enums.rs"]
#[allow(clippy::all)]
mod enums;
#[path = "gen/fields.rs"]
#[allow(clippy::all)]
mod fields;
#[path = "gen/fp_math.rs"]
#[allow(clippy::all)]
mod fp_math;
#[path = "gen/integer_math.rs"]
#[allow(clippy::all)]
mod integer_math;
#[path = "gen/lists.rs"]
#[allow(clippy::all)]
mod lists;
#[path = "gen/logic.rs"]
#[allow(clippy::all)]
mod logic;
#[path = "gen/macros.rs"]
#[allow(clippy::all)]
mod macros;
#[path = "gen/macros2.rs"]
#[allow(clippy::all)]
mod macros2;
#[path = "gen/math_ext.rs"]
#[allow(clippy::all)]
mod math_ext;
#[path = "gen/namespace.rs"]
#[allow(clippy::all)]
mod namespace;
#[path = "gen/optionals.rs"]
#[allow(clippy::all)]
mod optionals;
#[path = "gen/parse.rs"]
#[allow(clippy::all)]
mod parse;
#[path = "gen/plumbing.rs"]
#[allow(clippy::all)]
mod plumbing;
#[path = "gen/proto2.rs"]
#[allow(clippy::all)]
mod proto2;
#[path = "gen/proto2_ext.rs"]
#[allow(clippy::all)]
mod proto2_ext;
#[path = "gen/proto3.rs"]
#[allow(clippy::all)]
mod proto3;
#[path = "gen/string.rs"]
#[allow(clippy::all)]
mod string;
#[path = "gen/string_ext.rs"]
#[allow(clippy::all)]
mod string_ext;
#[path = "gen/timestamps.rs"]
#[allow(clippy::all)]
mod timestamps;
#[path = "gen/type_deduction.rs"]
#[allow(clippy::all)]
mod type_deduction;
#[path = "gen/unknowns.rs"]
#[allow(clippy::all)]
mod unknowns;
#[path = "gen/wrappers.rs"]
#[allow(clippy::all)]
mod wrappers;
